# Generated by Django 3.2 on 2024-10-31 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel_de_poder', models.IntegerField(default=0)),
                ('asesinatos', models.IntegerField(default=0)),
                ('veces_que_ha_muerto', models.IntegerField(default=0)),
                ('raza', models.CharField(max_length=50)),
                ('organizacion', models.CharField(max_length=50)),
                ('planetas_destruidos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sayayin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel_de_poder', models.IntegerField(default=0)),
                ('veces_ha_resucitado', models.IntegerField(default=0)),
                ('torneos_ganados', models.IntegerField(default=0)),
                ('edad', models.IntegerField(default=0)),
                ('maestro', models.CharField(max_length=50)),
                ('transformacion_max', models.CharField(max_length=50)),
                ('descripcion_breve', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enfrentamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=15)),
                ('ubicacion', models.CharField(max_length=30)),
                ('saga', models.CharField(max_length=50)),
                ('enemigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos', to='enemigosapp.enemigo')),
                ('sayayin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos', to='enemigosapp.sayayin')),
            ],
        ),
    ]
