# Generated by Django 3.2 on 2024-11-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemigosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfrentamientos',
            name='resultado',
            field=models.CharField(max_length=20),
        ),
    ]
