# Generated by Django 3.2 on 2024-11-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemigosapp', '0002_alter_enfrentamientos_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfrentamientos',
            name='resultado',
            field=models.CharField(choices=[('gana sayayin', 'Gana Sayayin'), ('gana enemigo', 'Gana Enemigo'), ('empate', 'Empate')], default='ganado', max_length=15),
        ),
    ]
